// <auto-generated />
namespace FsUniversityApi.Migrations

open System
open FsUniversityApi.Database
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<FsDbContext.FsDbContext>)>]
[<Migration("20230721141206_InitialMigration")>]
type InitialMigration() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "_Professors"
            ,columns = (fun table -> 
            {|
                ProfessorId =
                    table.Column<Guid>(
                        nullable = false
                        ,``type`` = "uniqueidentifier"
                    )
                IdCode =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(max)"
                    )
                Subject =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(max)"
                    )
            |})
            , constraints =
                (fun table -> 
                    table.PrimaryKey("PK__Professors", (fun x -> (x.ProfessorId) :> obj)
                    ) |> ignore
                )
        ) |> ignore

        migrationBuilder.InsertData(
            table = "_Professors",
            columns = [| "ProfessorId"; "IdCode"; "Subject" |],
            values = [| Guid("ed682c7a-4c35-438a-a2d2-6617866d8740") :> obj; "22222" :> obj; "Mathematics" :> obj |]
        ) |> ignore

        migrationBuilder.InsertData(
            table = "_Professors",
            columns = [| "ProfessorId"; "IdCode"; "Subject" |],
            values = [| Guid("eefa10cf-46ea-4ad2-b0f3-0198c9654059") :> obj; "11111" :> obj; "Programming" :> obj |]
        ) |> ignore

        migrationBuilder.InsertData(
            table = "_Professors",
            columns = [| "ProfessorId"; "IdCode"; "Subject" |],
            values = [| Guid("fc8a763c-88f0-4e96-b40f-387e70c2f824") :> obj; "33333" :> obj; "Physics" :> obj |]
        ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "_Professors"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 128) |> ignore

        modelBuilder.Entity("FsUniversityApi.Database.Entities.Professor+Professor", (fun b ->

            b.Property<Guid>("ProfessorId")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier")
                |> ignore

            b.Property<string>("IdCode")
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.Property<string>("Subject")
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.HasKey("ProfessorId")
                |> ignore


            b.ToTable("_Professors") |> ignore


            b.HasData([|
                {| ProfessorId = Guid("eefa10cf-46ea-4ad2-b0f3-0198c9654059"); IdCode = "11111"; Subject = "Programming" |}
                {| ProfessorId = Guid("ed682c7a-4c35-438a-a2d2-6617866d8740"); IdCode = "22222"; Subject = "Mathematics" |}
                {| ProfessorId = Guid("fc8a763c-88f0-4e96-b40f-387e70c2f824"); IdCode = "33333"; Subject = "Physics" |}
             |]) |> ignore
        )) |> ignore

