// <auto-generated />
namespace FsUniversityApi.Migrations

open System
open FsUniversityApi.Database
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<FsDbContext.FsDbContext>)>]
type FsDbContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 128) |> ignore

        modelBuilder.Entity("FsUniversityApi.Database.Entities.Professor+Professor", (fun b ->

            b.Property<Guid>("ProfessorId")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier")
                |> ignore

            b.Property<string>("IdCode")
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.Property<string>("Subject")
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.HasKey("ProfessorId")
                |> ignore


            b.ToTable("_Professors") |> ignore


            b.HasData([|
                {| ProfessorId = Guid("eefa10cf-46ea-4ad2-b0f3-0198c9654059"); IdCode = "11111"; Subject = "Programming" |}
                {| ProfessorId = Guid("ed682c7a-4c35-438a-a2d2-6617866d8740"); IdCode = "22222"; Subject = "Mathematics" |}
                {| ProfessorId = Guid("fc8a763c-88f0-4e96-b40f-387e70c2f824"); IdCode = "33333"; Subject = "Physics" |}
             |]) |> ignore
        )) |> ignore

